easy_admin:
  entities:
    Category:
      class: App\Entity\Category
      label: Catégories
      help: Liste des catégories du forum
      list:
        fields:
          - id
          - { property: 'name', label: 'Nom' }
      form:
        fields:
          - { property: 'name', label: 'Nom' }
      show:
        help: null
        fields:
          - id
          - { property: 'name', label: 'Nom' }
          - { property: 'subcategories', label: 'Sous-catégories' }
      new:
        title: 'Nouvelle catégorie'
        help: null
      edit:
        title: 'Éditer une catégorie'
        help: null
