easy_admin:
  entities:
    User:
      class: App\Entity\User
      label: Membres
      help: Liste des membres du forum
      list:
        fields:
          - id
          - { property: 'avatar', type: 'image', base_path: '%app.path.user_avatar%', label: 'Avatar' }
          - { property: 'username', label: "Nom d'utilisateur" }
          - { property: 'email', label: 'Adresse email' }
          - { property: 'roles', label: 'Rôle'}
          - { property: 'createdAt', label: "Date d'inscription"}
          - { property: 'confirmed', label: 'Confirmé' }
      form:
        fields:
          - { property: 'imageFile', label: 'Avatar', type: 'file', type_options: { required: false }}
          - { property: 'username', label: "Nom d'utilisateur" }
          - { property: 'email', label: 'Adresse email' }
      show:
        help: null
        fields:
          - id
          - { property: 'avatar', type: 'image', base_path: '%app.path.user_avatar%', label: 'Avatar' }
          - { property: 'username', label: "Nom d'utilisateur" }
          - { property: 'email', label: 'Adresse email' }
          - { property: 'roles', label: 'Rôles', type: 'array' }
          - { property: 'createdAt', label: "Date d'inscription" }
          - { property: 'topics', label: 'Sujets crées' }
      new:
        title: 'Nouveau membre'
        help: null
        fields:
          - { property: 'password', type: 'password', label: 'Mot de passe' }
          - { property: 'roles', label: 'Rôles', type: 'collection', help: 'Les rôles disponibles sont pour le moment dans le fichier security.yaml' }
      edit:
        title: 'Éditer un membre'
        help: null
        fields:
          - { property: 'password', type: 'password', label: 'Mot de passe' }
          - { property: 'roles', label: 'Rôles', type: 'collection', help: 'Les rôles disponibles sont pour le moment dans le fichier security.yaml' }
